blueprint:
  name: Lutron Pico 5 Button - Fan Control
  description: Control a fan with a Lutron Pico 5 Button remote (increase/decrease speed and toggle direction).
  domain: automation

  input:
    pico_1:
      name: Pico Device
      description: Pico remote to associate with fan entity.
      selector:
        device:
          model: PJ2-3BRL-XXX-F01 (Pico3ButtonRaiseLower)
          multiple: false

    fan_entity:
      name: Fan Entity
      description: Fan entity to control (must support increase/decrease speed, and direction).
      selector:
        entity:
          domain:
            - fan
          multiple: false

trigger:
  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: 'on'
    id: on_pressed

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: raise
    id: up_pressed

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: release
    subtype: raise
    id: up_released

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: stop
    id: stop_pressed

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: lower
    id: down_pressed

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: release
    subtype: lower
    id: down_released

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: 'off'
    id: off_pressed

action:
  # Store fan entity in a variable so we don't call "!input fan_entity" inside templates
  - variables:
      fan_var: !input fan_entity

  - choose:
      # ============== ON Pressed ==============
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - service: fan.turn_on
            target:
              entity_id: !input fan_entity

      # ============== UP Pressed (Raise) ==============
      - conditions:
          - condition: trigger
            id: up_pressed
        sequence:
          - repeat:
              sequence:
                - service: fan.increase_speed
                  target:
                    entity_id: !input fan_entity
                - delay:
                    milliseconds: 500
              until:
                - condition: trigger
                  id: up_released

      # ============== STOP Pressed (Toggle Direction) ==============
      - conditions:
          - condition: trigger
            id: stop_pressed
        sequence:
          - variables:
              current_direction: "{{ state_attr(fan_var, 'direction') }}"
          - service: fan.set_direction
            data:
              entity_id: "{{ fan_var }}"
              direction: "{{ 'forward' if current_direction == 'reverse' else 'reverse' }}"

      # ============== DOWN Pressed (Lower) ==============
      - conditions:
          - condition: trigger
            id: down_pressed
        sequence:
          - repeat:
              sequence:
                - service: fan.decrease_speed
                  target:
                    entity_id: !input fan_entity
                - delay:
                    milliseconds: 500
              until:
                - condition: trigger
                  id: down_released

      # ============== OFF Pressed ==============
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - service: fan.turn_off
            target:
              entity_id: !input fan_entity

mode: restart
