blueprint:
  name: Lutron Pico 5 Button - Fan Control (Use fan.increase_speed)
  description: Control fan entities with a Lutron Pico 5 Button remote, using fan.increase_speed/fan.decrease_speed calls.
  domain: automation

  input:
    pico_1:
      name: Pico Device
      description: Pico remote to associate with fan entity.
      selector:
        device:
          model: PJ2-3BRL-XXX-F01 (Pico3ButtonRaiseLower)
          multiple: false

    fan_entity:
      name: Fan Entity
      description: Fan entity to control (must support increase/decrease speed).
      selector:
        entity:
          domain:
            - fan
          multiple: false

trigger:
  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: 'on'
    id: on_pressed

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: raise
    id: up_pressed

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: release
    subtype: raise
    id: up_released

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: stop
    id: stop_pressed

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: lower
    id: down_pressed

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: release
    subtype: lower
    id: down_released

  - platform: device
    device_id: !input pico_1
    domain: lutron_caseta
    type: press
    subtype: 'off'
    id: off_pressed

action:
  - choose:
      # ============== ON Pressed ==============
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - service: fan.turn_on
            target:
              entity_id: !input fan_entity

      # ============== UP Pressed (Raise) ==============
      - conditions:
          - condition: trigger
            id: up_pressed
        sequence:
          - repeat:
              sequence:
                - service: fan.increase_speed
                  target:
                    entity_id: !input fan_entity
                - delay:
                    milliseconds: 500
              until:
                - condition: trigger
                  id: up_released

      # ============== DOWN Pressed (Lower) ==============
      - conditions:
          - condition: trigger
            id: down_pressed
        sequence:
          - repeat:
              sequence:
                - service: fan.decrease_speed
                  target:
                    entity_id: !input fan_entity
                - delay:
                    milliseconds: 500
              until:
                - condition: trigger
                  id: down_released

      # ============== OFF Pressed ==============
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - service: fan.turn_off
            target:
              entity_id: !input fan_entity

mode: restart
